# -*- mode: python ; coding: utf-8 -*-
import os
import sys

block_cipher = None

SRC_DIR = os.path.join(SPECPATH, 'src')
ASSETS_DIR = os.path.join(SPECPATH, 'assets')
CONFIG_DIR = os.path.join(SPECPATH, 'config')

a = Analysis(
    [os.path.join(SRC_DIR, 'main.py')],
    pathex=[SRC_DIR],
    binaries=[],
    datas=[
        (ASSETS_DIR, 'assets'),
        (CONFIG_DIR, 'config'),
    ],
    hiddenimports=[
        'numpy',
        'scipy',
        'scipy.optimize',
        'scipy.special',
        'scipy.fft',
        'scipy.signal',
        'scipy.ndimage',
        'scipy.signal._peak_finding',
        'PyQt6',
        'PyQt6.QtWidgets',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWebEngineWidgets',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtWebChannel',
        'PyQt6.QtSvg',
        'pyqtgraph',
        'pyqtgraph.graphicsItems',
        'pyqtgraph.graphicsItems.PlotItem',
        'pyqtgraph.graphicsItems.ViewBox',
        'pyqtgraph.graphicsItems.PlotCurveItem',
        'pyqtgraph.graphicsItems.ImageItem',
        'pyqtgraph.graphicsItems.BarGraphItem',
        'pyqtgraph.graphicsItems.LegendItem',
        'pyqtgraph.graphicsItems.AxisItem',
        'pyqtgraph.graphicsItems.ImageView',
        'pyqtgraph.graphicsItems.GradientEditorItem',
        'pyqtgraph.graphicsItems.LinearRegionItem',
        'pyqtgraph.graphicsItems.InfiniteLine',
        'pyqtgraph.graphicsItems.ROI',
        'pyqtgraph.exporters',
        'pyqtgraph.exporters.ImageExporter',
        'cv2',
        'PIL',
        'PIL.Image',
        'h5py',
        'h5py.defs',
        'numba',
        'yaml',
        'tifffile',
        'markdown',
        'markdown.extensions',
        'markdown.extensions.tables',
        'markdown.extensions.fenced_code',
        'matplotlib',
        'core',
        'core.aperture',
        'core.diffraction',
        'core.optics',
        'core.zernike',
        'core.chromatic',
        'core.units',
        'analysis',
        'analysis.psf_mtf',
        'analysis.fitting',
        'analysis.measurements',
        'gui',
        'gui.main_window',
        'gui.control_panel',
        'gui.canvas',
        'gui.data_panel',
        'gui.profile_plot',
        'gui.colormaps',
        'gui.shape_editor',
        'gui.dialogs',
        'gui.dialogs.help_dialog',
        'gui.dialogs.analysis_dialog',
        'gui.dialogs.settings_dialog',
        'gui.dialogs.export_dialog',
        'gui.dialogs.about_dialog',
        'gui.dialogs.parameter_scan_dialog',
        'gui.dialogs.chromatic_diffraction_dialog',
        'gui.dialogs.fitting_dialog',
        'gui.dialogs.wavefront_dialog',
        'gui.dialogs.propagation_dialog',
        'gui.dialogs.optical_scene_dialog',
        'gui.dialogs.receiver_surface_dialog',
        'gui.dialogs.dialog_theme',
        'utils',
        'utils.config',
        'utils.logger',
        'utils.io_handler',
        'utils.preferences',
        'csv',
        'json',
        'hashlib',
        'math',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
        'cupy',
        'CUDA',
    ],
    noarchive=False,
    optimize=0,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='EM Field Studio',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='EM Field Studio',
)
